; Generated by node scripts/generate-desktop-bitmap-assets.mjs. Do not edit.
; Source: docs/mockup/index.html (original approved glyphs/drawing functions).
; Mock script SHA-256: a6805f83948b9cedea1c9a439933bc3c0e25fb4d65e66b12c4d798c9fdd90d8c
; 1 = black ink; 0 = white. All rows are MSB first, left to right.
; Font is ASCII $20..$7f: five high bits, seven rows plus a blank eighth.
; Uppercase and lowercase have distinct art; unsupported characters use question mark.
; Icons are row-major: three consecutive bytes per row, sixteen rows each.
; These are source rasters, not VIC-II cell-interleaved bitmap memory.

GeosRichFontFirst = $20
GeosRichFontCount = 96
GeosRichFontWidth = 5
GeosRichFontHeight = 7
GeosRichFontAdvance = 6
GeosRichFontStride = 8
GeosRichIconWidth = 24
GeosRichIconHeight = 16
GeosRichIconRowBytes = 3
GeosRichIconStride = 48
GeosRichIconCount = 8
GeosRichBrowserIconCount = 4
GeosRichBrowserIconStride = 48

GeosRichFont:
   !byte $00,$00,$00,$00,$00,$00,$00,$00 ; $20 " "
   !byte $20,$20,$20,$20,$20,$00,$20,$00 ; $21 "!"
   !byte $50,$50,$50,$00,$00,$00,$00,$00 ; $22 "\""
   !byte $50,$f8,$50,$50,$f8,$50,$50,$00 ; $23 "#"
   !byte $20,$78,$a0,$70,$28,$f0,$20,$00 ; $24 "$"
   !byte $c8,$d0,$20,$40,$b0,$30,$00,$00 ; $25 "%"
   !byte $60,$90,$a0,$40,$a8,$90,$68,$00 ; $26 "&"
   !byte $20,$20,$40,$00,$00,$00,$00,$00 ; $27 "'"
   !byte $10,$20,$40,$40,$40,$20,$10,$00 ; $28 "("
   !byte $40,$20,$10,$10,$10,$20,$40,$00 ; $29 ")"
   !byte $00,$20,$a8,$70,$a8,$20,$00,$00 ; $2a "*"
   !byte $00,$20,$20,$f8,$20,$20,$00,$00 ; $2b "+"
   !byte $00,$00,$00,$00,$30,$20,$40,$00 ; $2c ","
   !byte $00,$00,$00,$f8,$00,$00,$00,$00 ; $2d "-"
   !byte $00,$00,$00,$00,$00,$30,$30,$00 ; $2e "."
   !byte $08,$10,$20,$40,$80,$00,$00,$00 ; $2f "/"
   !byte $70,$88,$98,$a8,$c8,$88,$70,$00 ; $30 "0"
   !byte $20,$60,$20,$20,$20,$20,$70,$00 ; $31 "1"
   !byte $70,$88,$08,$10,$20,$40,$f8,$00 ; $32 "2"
   !byte $f0,$08,$08,$70,$08,$08,$f0,$00 ; $33 "3"
   !byte $10,$30,$50,$90,$f8,$10,$10,$00 ; $34 "4"
   !byte $f8,$80,$80,$f0,$08,$08,$f0,$00 ; $35 "5"
   !byte $70,$80,$80,$f0,$88,$88,$70,$00 ; $36 "6"
   !byte $f8,$08,$10,$20,$40,$40,$40,$00 ; $37 "7"
   !byte $70,$88,$88,$70,$88,$88,$70,$00 ; $38 "8"
   !byte $70,$88,$88,$78,$08,$08,$70,$00 ; $39 "9"
   !byte $00,$30,$30,$00,$30,$30,$00,$00 ; $3a ":"
   !byte $00,$30,$30,$00,$30,$20,$40,$00 ; $3b ";"
   !byte $08,$10,$20,$40,$20,$10,$08,$00 ; $3c "<"
   !byte $00,$00,$f8,$00,$f8,$00,$00,$00 ; $3d "="
   !byte $80,$40,$20,$10,$20,$40,$80,$00 ; $3e ">"
   !byte $70,$88,$08,$10,$20,$00,$20,$00 ; $3f "?"
   !byte $70,$88,$b8,$a8,$b8,$80,$70,$00 ; $40 "@"
   !byte $70,$88,$88,$f8,$88,$88,$88,$00 ; $41 "A"
   !byte $f0,$88,$88,$f0,$88,$88,$f0,$00 ; $42 "B"
   !byte $78,$80,$80,$80,$80,$80,$78,$00 ; $43 "C"
   !byte $f0,$88,$88,$88,$88,$88,$f0,$00 ; $44 "D"
   !byte $f8,$80,$80,$f0,$80,$80,$f8,$00 ; $45 "E"
   !byte $f8,$80,$80,$f0,$80,$80,$80,$00 ; $46 "F"
   !byte $78,$80,$80,$b8,$88,$88,$78,$00 ; $47 "G"
   !byte $88,$88,$88,$f8,$88,$88,$88,$00 ; $48 "H"
   !byte $f8,$20,$20,$20,$20,$20,$f8,$00 ; $49 "I"
   !byte $38,$10,$10,$10,$90,$90,$60,$00 ; $4a "J"
   !byte $88,$90,$a0,$c0,$a0,$90,$88,$00 ; $4b "K"
   !byte $80,$80,$80,$80,$80,$80,$f8,$00 ; $4c "L"
   !byte $88,$d8,$a8,$a8,$88,$88,$88,$00 ; $4d "M"
   !byte $88,$c8,$a8,$98,$88,$88,$88,$00 ; $4e "N"
   !byte $70,$88,$88,$88,$88,$88,$70,$00 ; $4f "O"
   !byte $f0,$88,$88,$f0,$80,$80,$80,$00 ; $50 "P"
   !byte $70,$88,$88,$88,$a8,$90,$68,$00 ; $51 "Q"
   !byte $f0,$88,$88,$f0,$a0,$90,$88,$00 ; $52 "R"
   !byte $78,$80,$80,$70,$08,$08,$f0,$00 ; $53 "S"
   !byte $f8,$20,$20,$20,$20,$20,$20,$00 ; $54 "T"
   !byte $88,$88,$88,$88,$88,$88,$70,$00 ; $55 "U"
   !byte $88,$88,$88,$88,$88,$50,$20,$00 ; $56 "V"
   !byte $88,$88,$88,$a8,$a8,$a8,$50,$00 ; $57 "W"
   !byte $88,$88,$50,$20,$50,$88,$88,$00 ; $58 "X"
   !byte $88,$88,$50,$20,$20,$20,$20,$00 ; $59 "Y"
   !byte $f8,$08,$10,$20,$40,$80,$f8,$00 ; $5a "Z"
   !byte $70,$40,$40,$40,$40,$40,$70,$00 ; $5b "["
   !byte $80,$40,$20,$10,$08,$00,$00,$00 ; $5c "\\"
   !byte $70,$10,$10,$10,$10,$10,$70,$00 ; $5d "]"
   !byte $20,$50,$88,$00,$00,$00,$00,$00 ; $5e "^"
   !byte $00,$00,$00,$00,$00,$00,$f8,$00 ; $5f "_"
   !byte $40,$20,$10,$00,$00,$00,$00,$00 ; $60 "`"
   !byte $00,$00,$70,$08,$78,$88,$78,$00 ; $61 "a"
   !byte $80,$80,$b0,$c8,$88,$88,$f0,$00 ; $62 "b"
   !byte $00,$00,$78,$80,$80,$80,$78,$00 ; $63 "c"
   !byte $08,$08,$68,$98,$88,$88,$78,$00 ; $64 "d"
   !byte $00,$00,$70,$88,$f8,$80,$78,$00 ; $65 "e"
   !byte $30,$48,$40,$e0,$40,$40,$40,$00 ; $66 "f"
   !byte $00,$78,$88,$88,$78,$08,$70,$00 ; $67 "g"
   !byte $80,$80,$b0,$c8,$88,$88,$88,$00 ; $68 "h"
   !byte $20,$00,$60,$20,$20,$20,$70,$00 ; $69 "i"
   !byte $10,$00,$30,$10,$10,$90,$60,$00 ; $6a "j"
   !byte $80,$80,$90,$a0,$c0,$a0,$90,$00 ; $6b "k"
   !byte $60,$20,$20,$20,$20,$20,$70,$00 ; $6c "l"
   !byte $00,$00,$d0,$a8,$a8,$a8,$a8,$00 ; $6d "m"
   !byte $00,$00,$b0,$c8,$88,$88,$88,$00 ; $6e "n"
   !byte $00,$00,$70,$88,$88,$88,$70,$00 ; $6f "o"
   !byte $00,$f0,$88,$88,$f0,$80,$80,$00 ; $70 "p"
   !byte $00,$78,$88,$88,$78,$08,$08,$00 ; $71 "q"
   !byte $00,$00,$b8,$c0,$80,$80,$80,$00 ; $72 "r"
   !byte $00,$00,$78,$80,$70,$08,$f0,$00 ; $73 "s"
   !byte $40,$40,$e0,$40,$40,$48,$30,$00 ; $74 "t"
   !byte $00,$00,$88,$88,$88,$98,$68,$00 ; $75 "u"
   !byte $00,$00,$88,$88,$88,$50,$20,$00 ; $76 "v"
   !byte $00,$00,$88,$88,$a8,$a8,$50,$00 ; $77 "w"
   !byte $00,$00,$88,$50,$20,$50,$88,$00 ; $78 "x"
   !byte $00,$88,$88,$88,$78,$08,$70,$00 ; $79 "y"
   !byte $00,$00,$f8,$10,$20,$40,$f8,$00 ; $7a "z"
   !byte $10,$20,$20,$40,$20,$20,$10,$00 ; $7b "{"
   !byte $20,$20,$20,$20,$20,$20,$20,$00 ; $7c "|"
   !byte $40,$20,$20,$10,$20,$20,$40,$00 ; $7d "}"
   !byte $00,$00,$40,$a8,$10,$00,$00,$00 ; $7e "~"
   !byte $70,$88,$08,$10,$20,$00,$20,$00 ; $7f DEL (question mark)
GeosRichFontEnd:

GeosRichIcons:
GeosRichIconTeensy:
   !byte $03,$33,$30
   !byte $03,$33,$30
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $0e,$7c,$70
   !byte $0e,$10,$70
   !byte $0e,$10,$70
   !byte $0e,$10,$70
   !byte $0e,$10,$70
   !byte $0e,$10,$70
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $03,$33,$30
   !byte $03,$33,$30
GeosRichIconSD:
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
   !byte $0f,$e4,$b0
   !byte $0c,$04,$b0
   !byte $0c,$04,$b0
   !byte $0c,$00,$30
   !byte $0c,$1e,$30
   !byte $0c,$20,$30
   !byte $0c,$20,$30
   !byte $0c,$1c,$30
   !byte $0c,$02,$30
   !byte $0c,$02,$30
   !byte $0c,$3c,$30
   !byte $0f,$ff,$f0
   !byte $0f,$ff,$f0
GeosRichIconUSB:
   !byte $00,$00,$00
   !byte $00,$00,$00
   !byte $00,$00,$00
   !byte $00,$00,$00
   !byte $3f,$ff,$80
   !byte $3f,$ff,$80
   !byte $3f,$ff,$fe
   !byte $38,$07,$ea
   !byte $38,$07,$fe
   !byte $38,$07,$fe
   !byte $3f,$ff,$fe
   !byte $3f,$ff,$80
   !byte $3f,$ff,$80
   !byte $00,$00,$00
   !byte $00,$00,$00
   !byte $00,$00,$00
GeosRichIconDrive8:
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$00,$1c
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $3c,$22,$3c
   !byte $3c,$22,$3c
   !byte $3c,$1c,$3c
   !byte $3c,$22,$3c
   !byte $3c,$22,$3c
   !byte $3f,$ff,$fc
GeosRichIconDrive9:
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$01,$9c
   !byte $38,$00,$1c
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $3f,$ff,$fc
   !byte $3c,$22,$3c
   !byte $3c,$22,$3c
   !byte $3c,$1e,$3c
   !byte $3c,$02,$3c
   !byte $3c,$02,$3c
   !byte $3f,$ff,$fc
GeosRichIconGames:
   !byte $00,$00,$00
   !byte $3f,$f0,$00
   !byte $3f,$f0,$00
   !byte $3f,$f0,$00
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $cf,$ff,$f3
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
GeosRichIconUtilities:
   !byte $00,$00,$00
   !byte $3f,$f0,$00
   !byte $3f,$f0,$00
   !byte $3f,$f0,$00
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $cf,$ff,$f3
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $c0,$00,$03
   !byte $ff,$ff,$ff
   !byte $ff,$ff,$ff
GeosRichIconControl:
   !byte $7f,$ff,$fe
   !byte $7f,$ff,$fe
   !byte $60,$c0,$06
   !byte $60,$c0,$06
   !byte $67,$ff,$e6
   !byte $60,$c0,$06
   !byte $60,$c1,$86
   !byte $60,$01,$86
   !byte $67,$ff,$e6
   !byte $60,$01,$86
   !byte $60,$19,$86
   !byte $60,$18,$06
   !byte $67,$ff,$e6
   !byte $60,$18,$06
   !byte $7f,$ff,$fe
   !byte $7f,$ff,$fe
GeosRichIconsEnd:

; Browser icons use 3x2 TILE ORDER: three eight-byte glyphs across the top,
; then three across the bottom. Copy directly to the browser character font.
; Folder and unnumbered disk come from the original mock; document/program
; are preserved byte-for-byte from GeosDesktop.s GeosIconData (last two icons).
GeosRichBrowserIconData:
GeosRichBrowserIconFolder:
   !byte $00,$3f,$3f,$3f,$ff,$ff,$ff,$c0
   !byte $00,$f0,$f0,$f0,$ff,$ff,$ff,$00
   !byte $00,$00,$00,$00,$ff,$ff,$ff,$03
   !byte $c0,$cf,$c0,$c0,$c0,$c0,$ff,$ff
   !byte $00,$ff,$00,$00,$00,$00,$ff,$ff
   !byte $03,$f3,$03,$03,$03,$03,$ff,$ff
GeosRichBrowserIconDisk:
   !byte $3f,$3f,$38,$38,$38,$38,$38,$3f
   !byte $ff,$ff,$01,$01,$01,$01,$00,$ff
   !byte $fc,$fc,$9c,$9c,$9c,$9c,$1c,$fc
   !byte $3f,$3f,$3c,$3c,$3c,$3c,$3c,$3f
   !byte $ff,$ff,$00,$00,$00,$00,$00,$ff
   !byte $fc,$fc,$3c,$3c,$3c,$3c,$3c,$fc
GeosRichBrowserIconDocument:
   !byte $00,$07,$04,$04,$04,$04,$04,$04
   !byte $00,$ff,$02,$02,$02,$03,$00,$00
   !byte $00,$e0,$20,$20,$20,$e0,$20,$20
   !byte $04,$04,$04,$04,$04,$04,$07,$00
   !byte $ff,$00,$ff,$00,$fe,$00,$ff,$00
   !byte $20,$20,$20,$20,$20,$20,$e0,$00
GeosRichBrowserIconProgram:
   !byte $00,$00,$3f,$2a,$20,$3f,$20,$20
   !byte $00,$00,$ff,$80,$00,$ff,$00,$00
   !byte $00,$00,$fc,$04,$04,$fc,$04,$04
   !byte $27,$24,$24,$24,$27,$20,$3f,$00
   !byte $e7,$20,$27,$20,$e7,$00,$ff,$00
   !byte $e4,$04,$e4,$04,$c4,$04,$fc,$00
GeosRichBrowserIconDataEnd:
